### ISSUE TITLE
How to read 3mf file with python?

### ISSUE THREAD

**Issue by MevaliOeztuerk** [3MFConsortium/lib3mf#298]
Hello,  
I am Mevali from Germany and I am very thankful for your programming code, but I don't understand how to read a specific 3MF file (in Python) and get important values like (beam grid structures, verticals, material properties, etc) from the code.

many greetings,

Mevali

**Comment by drmattyg** [comment]
@martinweismann if no one is currently working on Python bindings for 3MF, I might be interested in giving it a shot.

**Comment by bdwilson24** [comment]
@

> @martinweismann if no one is currently working on Python bindings for 3MF, I might be interested in giving it a shot.

I think that's what this library is supposed to be, right? I'm stuck trying to figure out how to properly import and use it as well.

**Comment by lgarron** [comment]
I tried to read a file using the official Python bindings and after about half an hour I was still unable to piece together how to read from a file without crashing. I wasn't able to find any successful examples on GitHub either.

Using `uv` and after running `uv add lib3mf`:

```
from lib3mf import Reader, Wrapper

def main():
    wrapper = Wrapper("./.venv/lib/python3.13/site-packages/lib3mf/lib3mf")
    reader = Reader(None, wrapper)
    model = reader.ReadFromFile("./file.3mf")

if __name__ == "__main__":
    main()
```

This crashes with:

```
Traceback (most recent call last):
  File "/Users/lgarron/Downloads/py3mf/hello.py", line 17, in <module>
    main()
    ~~~~^^
  File "/Users/lgarron/Downloads/py3mf/hello.py", line 9, in main
    reader = Reader(None, wrapper)
  File "/Users/lgarron/Downloads/py3mf/.venv/lib/python3.13/site-packages/lib3mf/Lib3MF.py", line 4431, in __init__
    Base.__init__(self, handle, wrapper)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lgarron/Downloads/py3mf/.venv/lib/python3.13/site-packages/lib3mf/Lib3MF.py", line 4322, in __init__
    raise ELib3MFException(ErrorCodes.INVALIDPARAM)
lib3mf.Lib3MF.ELib3MFException: Lib3MFException 2
Exception ignored in: <function Base.__del__ at 0x1045a0180>
Traceback (most recent call last):
  File "/Users/lgarron/Downloads/py3mf/.venv/lib/python3.13/site-packages/lib3mf/Lib3MF.py", line 4327, in __del__
    self._wrapper.Release(self)
AttributeError: 'Reader' object has no attribute '_wrapper
```

I can't figure out what to pass as the "handle" for the first argument to `Reader` of if that's even related to the error.

If anyone else knows what's going on, I'd appreciate some pointers

**Comment by lgarron** [comment]
> @lgarron Here is a simple example to read a 3mf file using python bindings https://github.com/3MFConsortium/lib3mf/blob/master/SDK/Examples/Python/3mf_convert.py

Thanks, appreciate it!

Unfortunately, even if I replace the import line with `from lib3mf import get_wrapper, get_version` I seem to get the exact same error. 😕
